### ISSUE TITLE
installation guid

### ISSUE THREAD

**Issue by leschNUX** [FragJage/MqttOwfs#1]
hi,

can you write a simple installation guid?

br

**Comment by FragJage** [comment]
Yes, i can, but i have 2 questions :
 - do you need some help to build ?
 - on which platform do you want to install it ?

**Comment by leschNUX** [comment]
Hi,

i want install it on raspberry 3b and on a nuc intel x86.

I can build myself with an installation guid.

Br

**Comment by FragJage** [comment]
Hi,

Ok, i need few days to write this on the wiki. 
I'll get back to you when I'm done.

Br

**Comment by FragJage** [comment]
Hi,

The wiki is completed.
Open a new issue if you have any problem.

Br
