### ISSUE TITLE
owfs server restarts -> mqttowfs service stops

### ISSUE THREAD

**Issue by TomDeVlaminck** [FragJage/MqttOwfs#14]
Dear François,

First I want to wish you a good new year and may you have no corona or your family.
I would like to ask you something. As I am using your service now to feed my grafana, I noticed that the service stopped exacly at 2:01 AM every day. As it turns out I forgot that my small network router that runs openwrt reboots at that time every day. This device has as a sole purpose to run as an owserver. It is connected to a usb->onewire adaptor. The owserver server running on it servers several openhab instances and some RRD loggings by unix scripting. It is not so stable over time so I had to insert a cron entry that it restarts.

My question is now is it configurable as I looked in the code that does the owfs <-> socket (https://github.com/FragJage/owfscpp) I see this code : 

    try
    {
        m_OwfsSock.Send(sendBuffer, total);
    }
    catch(SimpleSock::Exception &e)
    {
        if(!m_Persistence) throw;
        m_PersistenceMode = PERSISTENCE_RETRY;
        Connect();
        m_OwfsSock.Send(sendBuffer, total);
    }

So I guess when the connection is lost it should reconnect if the mode is PERSISTENCE_RETRY.
But looking at the code of SimpleSock.cpp the open will fail as the owserver is unavailble as the host is restarting.

As a solution the main program loop could handle the error but not crash (deamon loop?) and so when the owserver is again active recover.

I see this as a great improvement because not only the owserver process can become temporily unavailable, but the network can go partially down or something else.

Could you please look into this, if there is a simple solution to it?
A simple test would be to setup a owfs server on a raspberry pi for example or a linux machine, stopping it and then on the other machine running mqttowfs seeing is the service stays alive and reconnects when the owfs becomes available.
It is also the same problem when the mqtt becomes tempory unavailable I think, but for my situation the mqttowfs service runs on the same host as the mosquitto service.

Greetings

Tom

<img width="682" alt="Screenshot 2021-01-07 at 22 31 08" src="https://user-images.githubusercontent.com/6303627/103947256-1bb81780-5138-11eb-820b-c95294ea7eda.png">

**Comment by FragJage** [comment]
Hello Tom,

I wish you a good new year.
In MqttOwfs there is a try/catch on owfscpp calls. You can see in MqttOwfs class, RefreshDevices method and OwGetValue method (m_OwfsClient is an instance of owfscpp class), example for OwGetValue l.227 :
```
    try
    {
        lock_guard<mutex> lock(m_OwfsClientAccess);
        m_OwfsClient.SetOwserverFlag(owfscpp::Uncached, uncachedRead);
        svalue = m_OwfsClient.Get(configName);
    }
    catch (const exception& e)
    {
        LOG_WARNING(m_Log) << "Unable to read " << configName << " : " << e.what();
        return "";
    }
```
The service should not stop but log warning "Unable to read ..." and try again a some time later, but I never tested this part of code.
I will try to reproduce it this weekend.
Best regard
FragJage

**Comment by FragJage** [comment]
I reproduce a freeze but not a stop. I try to implement no blocking socket for network communication.

**Comment by FragJage** [comment]
Hello Tom,
You can test improved network communication on main branch.
