### ISSUE TITLE
MQTT client id not in documentation

### ISSUE THREAD

**Issue by kettenbach-it** [FragJage/MqttOwfs#15]
Sorry,

my mistake: it is possible to set the client id by using "id=" in the config.
But this fact is not in the documentation https://github.com/FragJage/MqttDaemon/wiki/Configuration

~~Hi,~~

~~my MQTT Server VerneMQ rejects MqttOwfs to login, because of an empty client id:~~

```
vernemq    | 16:59:38.275 [warning] can't authenticate client {[],<<"anon-/4fHUQ6JX7jPeF4/r+hv+XflueY=">>} from 172.25.0.1:49058 due to invalid_credentials
vernemq    | 16:59:38.376 [warning] empty client id not allowed in mqttv3 {[],undefined}
```

~~In the documentation of MqttDaemon I see no way, to set the client_id, correct!?
Cloud it be possible to either implement it or set it to a fixe value like "mqttowfs"~~

~~You can see here http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html in section 3.1 that "All but the Client identifier are optional" => you need to set the client_id~~

**Comment by FragJage** [comment]
Hello,
Exact, the documentation is now completed.
Thanks.
