### ISSUE TITLE
mqttlog not working?

### ISSUE THREAD

**Issue by migube** [FragJage/MqttOwfs#16]
bjr bjr

I just compiled MqttOwfs , as I'm looking for a solution to send mqtt messages to Home assistant on state changes of ds2408 latch.ALL, ...

not yet sure it will work, new to HA & MQTT https://www.home-assistant.io/docs/mqtt/discovery/

Now, I don't see any messages published subscribing to the topic with mqttlens
(while I see them if I manually publish from homeassistant)

I tried lg debugging
https://github.com/FragJage/MqttDaemon/wiki/Configuration

`[mqttlog]
enable=true
level=7`

`sudo MqttOwfs -restart 
root@DietPi:/# 2021-01-23 20:45:23 ERROR MqttOwfs.cpp l.136 DevicesConfigure Device 'mqttlog' is improperly formatted, it must contain a '/'.
`

So the mqttlog section is not recognized ?

I can see the client is registered in the mosquito broker. no messages there either though not sure

owserver reading is ok
2021-01-23 20:28:56 VERBOSE MqttOwfs.cpp l.283 OwDeviceAdd Device created 'LatchALLdoors' : '29.8B1000000000/latch.ALL' (round -1)
2021-01-23 20:28:56 TRACE MqttOwfs.cpp l.371 RefreshValue Read value for '29.8B1000000000/latch.ALL'
2021-01-23 20:28:56 VERBOSE MqttOwfs.cpp l.380 RefreshValue New value for '29.8B1000000000/latch.ALL' : '0,0,0,0,0,0,1,0'
2021-01-23 20:28:57 DEBUG MqttOwfs.cpp l.494 DaemonLoop *** Enter ***

merci!

**Comment by FragJage** [comment]
Bonjour,
Topic for one wire devices is owfs/#, topic for log message is logger/owfs/#.
So for 28.C2E1BE000000 device, value is send to topic owfs/28.C2E1BE000000/temperature.
MqttOwfs not send the temperature if read 85°C.
To read a specific value of a DS2450 you can add a new section in configuration file : 
```
[20.FC4D05000000/volt.A]
displayname = DS2450voltageA
```
-> Send the value of 20.FC4D05000000/volt.A on topic owfs/DS2450voltageA.
With this section, automatic detection is disabled for 20.FC4D05000000 so PIO.A to D are not send, if you want there values, add others sections as [20.FC4D05000000/PIO.A] etc, but you can't hide a device automatically detected.
It's not possible to change the format of mqtt message.
I don't known the format for HA, i think it can read topic owfs/# but not logger/owfs/#.

I think i have answer to all questions.
Best regards

**Comment by FragJage** [comment]
For the log `DevicesConfigure Device 'mqttlog' is improperly formatted, it must contain a '/'. `, it's minor bug, i fix it this week : mqttlog section is confused with a device section.

**Comment by FragJage** [comment]
Fix on main branch.
