### ISSUE TITLE
build succesfull but can't starting daemon

### ISSUE THREAD

**Issue by leschNUX** [FragJage/MqttOwfs#2]
Hi,

build on a nux ubuntu x86_64
` make
Scanning dependencies of target MqttOwfs
[  2%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/FragFramework/                                                                                        src/Plateforms.cpp.o
[  5%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/FragFramework/                                                                                        src/SafeFunctions.cpp.o
[  8%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/FragFramework/                                                                                        src/StringTools.cpp.o
[ 10%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/MqttDaemon/src                                                                                        /MqttDaemon.cpp.o
[ 13%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/MqttDaemon/src                                                                                        /MqttClient.cpp.o
[ 16%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/MqttDaemon/src                                                                                        /MqttBase.cpp.o
[ 18%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/owfscpp/src/ow                                                                                        fscpp.cpp.o
[ 21%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/ServiceSkeleto                                                                                        n/src/Service.cpp.o
[ 24%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/SimpleFolder/s                                                                                        rc/SimpleFolders.cpp.o
[ 27%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/SimpleIni/src/                                                                                        SimpleIni.cpp.o
[ 29%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/SimpleLog/src/                                                                                        SimpleLog.cpp.o
[ 32%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/SimpleSock/src                                                                                        /SimpleSock.cpp.o
[ 35%] Building CXX object src/CMakeFiles/MqttOwfs.dir/__/dependencies/SimpleSock/src                                                                                        /SimpleSockTCP.cpp.o
[ 37%] Building CXX object src/CMakeFiles/MqttOwfs.dir/MqttOwfs.cpp.o
/opt/MqttOwfs/src/MqttOwfs.cpp:427:30: warning: unused parameter ‘argc’ [-Wunused-par                                                                                        ameter]
 int MqttOwfs::DaemonLoop(int argc, char* argv[])
                              ^
/opt/MqttOwfs/src/MqttOwfs.cpp:427:47: warning: unused parameter ‘argv’ [-Wunused-par                                                                                        ameter]
 int MqttOwfs::DaemonLoop(int argc, char* argv[])
                                               ^
[ 40%] Building CXX object src/CMakeFiles/MqttOwfs.dir/owDevice.cpp.o
[ 43%] Building CXX object src/CMakeFiles/MqttOwfs.dir/main.cpp.o
[ 45%] Linking CXX executable bin/MqttOwfs
[ 45%] Built target MqttOwfs
Scanning dependencies of target unittest
[ 48%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/FragFramework                                                                                        /src/StringTools.cpp.o
[ 51%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/FragFramework                                                                                        /src/Plateforms.cpp.o
[ 54%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/FragFramework                                                                                        /src/SafeFunctions.cpp.o
[ 56%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/FragFramework                                                                                        /src/UnitTest.cpp.o
[ 59%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/MqttDaemon/sr                                                                                        c/MqttDaemon.cpp.o
[ 62%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/MqttDaemon/sr                                                                                        c/MqttClient.cpp.o
[ 64%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/MqttDaemon/sr                                                                                        c/MqttBase.cpp.o
[ 67%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/owfscpp/src/o                                                                                        wfscpp.cpp.o
[ 70%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/ServiceSkelet                                                                                        on/src/Service.cpp.o
[ 72%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/SimpleFolder/                                                                                        src/SimpleFolders.cpp.o
[ 75%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/SimpleIni/src                                                                                        /SimpleIni.cpp.o
[ 78%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/SimpleLog/src                                                                                        /SimpleLog.cpp.o
[ 81%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/SimpleSock/sr                                                                                        c/SimpleSock.cpp.o
[ 83%] Building CXX object test/CMakeFiles/unittest.dir/__/dependencies/SimpleSock/sr                                                                                        c/SimpleSockTCP.cpp.o
[ 86%] Building CXX object test/CMakeFiles/unittest.dir/__/src/MqttOwfs.cpp.o
/opt/MqttOwfs/src/MqttOwfs.cpp:427:30: warning: unused parameter ‘argc’ [-Wunused-par                                                                                        ameter]
 int MqttOwfs::DaemonLoop(int argc, char* argv[])
                              ^
/opt/MqttOwfs/src/MqttOwfs.cpp:427:47: warning: unused parameter ‘argv’ [-Wunused-par                                                                                        ameter]
 int MqttOwfs::DaemonLoop(int argc, char* argv[])
                                               ^
[ 89%] Building CXX object test/CMakeFiles/unittest.dir/__/src/owDevice.cpp.o
[ 91%] Building CXX object test/CMakeFiles/unittest.dir/TestowDevice.cpp.o
[ 94%] Building CXX object test/CMakeFiles/unittest.dir/TestMqttOwfs.cpp.o
/opt/MqttOwfs/test/TestMqttOwfs.cpp:158:41: warning: unused parameter ‘pMqttDev’ [-Wu                                                                                        nused-parameter]
 void TestMqttOwfs::ThreadConf(MqttOwfs* pMqttDev)
                                         ^
[ 97%] Building CXX object test/CMakeFiles/unittest.dir/main.cpp.o
[100%] Linking CXX executable bin/unittest
[100%] Built target unittest
`

/MqttOwfs
2019-01-31 21:05:33 ERROR MqttOwfs.cpp l.163 RefreshDevices Unable to find owdevices                                                                                         : SimpleSockTCP::Connect: unable to connect (system error 111)
^C
root@nuc:/opt/MqttOwfs/src/bin# ./MqttOwfs -f /etc/MqttOwfs/MqttOwfs.conf

Usage :
./MqttOwfs -start       To start the daemon
./MqttOwfs -stop        To stop the daemon
./MqttOwfs -restart     To restart the daemon
./MqttOwfs -console     To start on the console

**Comment by FragJage** [comment]
Hi,
socket error 111 => Connection refused.
Unable to connect to owserver.
You must specify -console to debug, or -start for daemon mode, so try
`./MqttOwfs -console -f /etc/MqttOwfs/MqttOwfs.conf`

**Comment by leschNUX** [comment]
works
