### ISSUE TITLE
refresh interfal for device,values and uncached

### ISSUE THREAD

**Issue by leschNUX** [FragJage/MqttOwfs#3]
Hi,

it was cool, to set the refresh interfall for devices, too. 

Like this:
[owfs]
server=192.168.10.58
port=4304
devicesinterval=5
valuesinterval=4

[28.FF633A751603/temperature9]
displayname = TemperatureSalon
round = 1
devicesinterval=1
valuesinterval=1
uncached= true

**Comment by FragXPL** [comment]
Hi,

Ok for valuesinterval and uncached, but i don't understand for devicesinterval.
It's a delay to rescan one-wire bus to find new devices.

**Comment by leschNUX** [comment]
Hi,

I used ds2401 for door and window status (open/closed).

Door open = ds2401 is not visible on the bus

Door closed = ds2401 is visible on the bus

I need for every ds2401 one second intervall but for ds18b20 not

**Comment by FragJage** [comment]
Hi,
OK, i understand. I don't known if it's possible to search one device, but i think it's possible to search all devices for a family (DS2401 for example).

**Comment by FragJage** [comment]
Hi,
3 new features :
- You can specify a specific refresh interval for a device with `refreshinterval` in device section.
- To force uncached read for a device, add `uncachedread = true` in device section.
- To verify if a device existing, create a device with `/ispresent` in title section, for example :
`[0100A00124DA00/ispresent]`
`displayname = door`
`refreshinterval = 1`
`uncachedread = true`

To test new features, fetch master branch, don't forget to fetch submodules with git submodule foreach git pull.

**Comment by leschNUX** [comment]
Hi,

update to new Version was successful, now i test it for refreshinterval feature
