### ISSUE TITLE
service unstable with the new feature

### ISSUE THREAD

**Issue by leschNUX** [FragJage/MqttOwfs#5]
Hi,

with the new feature, the service hangs.

My config:
[ID/ispresent]
displayname = Garagen_Tuer
refreshinterval = 1
uncachedread = true

[ID/ispresent]
displayname = Garagen_Tor_Offen
refreshinterval = 1
uncachedread = true

[ID/ispresent]
displayname = Garagen_Fenster
refreshinterval = 1
uncachedread = true

Log:
`May 19 22:59:52 nuc systemd[1]: mqttowfs.service: State 'stop-sigterm' timed out. Killing.
May 19 22:59:52 nuc systemd[1]: mqttowfs.service: Killing process 5840 (MqttOwfs) with signal SIGKILL.
May 19 22:59:52 nuc systemd[1]: mqttowfs.service: Failed with result 'timeout'.
May 19 22:59:57 nuc systemd[1]: mqttowfs.service: Service hold-off time over, scheduling restart.
`

**Comment by FragJage** [comment]
Hello,

The service hangs at startup or later?

**Comment by leschNUX** [comment]
HI,

service hangs later.

`Aug  2 22:50:15 nuc systemd[1]: mqttowfs.service: Killing process 30988 (MqttOwfs) with signal SIGKILL.
Aug  2 22:51:50 nuc systemd[1]: mqttowfs.service: Killing process 31690 (MqttOwfs) with signal SIGKILL.
Aug  2 22:53:28 nuc systemd[1]: mqttowfs.service: Killing process 32470 (MqttOwfs) with signal SIGKILL.
Aug  2 22:55:04 nuc systemd[1]: mqttowfs.service: Killing process 589 (MqttOwfs) with signal SIGKILL.
Aug  2 22:56:39 nuc systemd[1]: mqttowfs.service: Killing process 1297 (MqttOwfs) with signal SIGKILL.
Aug  2 22:58:15 nuc systemd[1]: mqttowfs.service: Killing process 1969 (MqttOwfs) with signal SIGKILL.`

**Comment by leschNUX** [comment]
`[2646]: 2019-08-02 22:59:39 TRACE MqttOwfs.cpp l.261 OwIsPresent Search presence of '01.XXXXXXXXX' with uncachedread to True
Aug  2 22:59:41 nuc mqttowfs[2646]: 2019-08-02 22:59:41 TRACE MqttOwfs.cpp l.276 OwIsPresent Found '1'
Aug  2 22:59:41 nuc mqttowfs[2646]: 2019-08-02 22:59:41 TRACE MqttOwfs.cpp l.356 RefreshValue Search device '01.XXXXXXXXXXX'
Aug  2 22:59:50 nuc systemd[1]: mqttowfs.service: Killing process 2663 (MqttOwfs) with signal SIGKILL.
Aug  2 22:59:50 nuc mqttowfs[2646]: 2019-08-02 22:59:41 TRACE MqttOwfs.cpp l.261 OwIsPresent Search pre
`

**Comment by FragJage** [comment]
Add mutex to protect simultaneous access to owfscpp class.
