### ISSUE TITLE
TCP/TLS connect failure

### ISSUE THREAD

**Issue by macsatcom** [FragJage/MqttOwfs#9]
I get a failure on connect.

I dont use TLS normally for my MQTT server, just running clear text.

Is it possible to connect using non-TLS ?

**Comment by FragJage** [comment]
I use a local mqtt server without TLS. You get a standard message of PAHO library when connection failed. Check your configuration file section mqtt value server, it should be like tcp://ip:port, more information on wiki https://github.com/FragJage/MqttOwfs/wiki/Configuration.
